-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[Bluetooth Transfer]====], [====[bluetooth-sendto]====]},
{[====[File Manager PCManFM]====], [====[pcmanfm]====]},
{[====[Files]====], [====[nautilus --new-window]====]},
{[====[Open a New Document]====], [====[gedit --new-document]====]},
{[====[Root Terminal]====], [====[gksu -l gnome-terminal]====]},
{[====[Sublime Text]====], [====[subl %F]====]},
{[====[Terminal]====], [====[gnome-terminal]====]},
{[====[Vi IMproved]====], [====[gvim -f %F]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
}
applicationsmenu[40] = {
{[====[Feh]====], [====[feh %f]====]}
}
applicationsmenu[50] = {
{[====[Aurora]====], [====[firefox-aurora %u]====]},
{[====[Aurora - Safe Mode]====], [====[firefox-aurora -safe-mode %u]====]},
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Chromium]====], [====[chromium]====]},
{[====[Dropbox]====], [====[dropboxd]====]},
{[====[Start Transmission Minimized]====], [====[transmission-gtk --minimized]====]},
{[====[Thunderbird]====], [====[thunderbird %u]====]},
{[====[Wicd]====], [====[/usr/bin/wicd-client]====]}
}
applicationsmenu[60] = {
{[====[Adobe Reader 9]====], [====[acroread]====]},
{[====[LibreOffice]====], [====[libreoffice]====]},
{[====[New Database]====], [====[libreoffice --base]====]},
{[====[New Document]====], [====[libreoffice --writer]====]},
{[====[New Drawing]====], [====[libreoffice --draw]====]},
{[====[New Formula]====], [====[libreoffice --math]====]},
{[====[New Presentation]====], [====[libreoffice --impress]====]},
{[====[New Spreadsheet]====], [====[libreoffice --calc]====]}
}
applicationsmenu[70] = {
{[====[Access Prompt]====], [====[/usr/lib/gcr/gcr-prompter]====]},
{[====[Aurora]====], [====[/opt/firefox-aurora/firefox %u]====]},
{[====[Connect to Server]====], [====[nautilus-connect-server]====]},
{[====[Desktop Icons]====], [====[nautilus --no-default-window --force-desktop]====]},
{[====[Evolution Calendar]====], [====[evolution -c calendar]====]},
{[====[GNOME Shell]====], [====[/usr/bin/gnome-shell]====]},
{[====[GNOME Shell Extension Preferences]====], [====[/usr/bin/gnome-shell-extension-prefs %u]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[Mutter]====], [====[mutter]====]},
{[====[Network]====], [====[nm-applet]====]},
{[====[Run Software]====], [====[nautilus-autorun-software %u]====]},
{[====[Thunderbird]====], [====[/usr/lib/thunderbird/thunderbird %u]====]},
{[====[View file]====], [====[/usr/bin/gcr-viewer]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[Eclipse]====], [====[eclipse]====]},
{[====[Emacs]====], [====[emacs %F]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]},
{[====[Qt4 QDbusViewer]====], [====[qdbusviewer-qt4]====]}
}
applicationsmenu[90] = {
{[====[Audacity]====], [====[audacity %F]====]},
{[====[gtkpod]====], [====[gtkpod]====]},
{[====[PulseAudio Volume Control]====], [====[pavucontrol]====]},
{[====[QT V4L2 test Utility]====], [====[qv4l2]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc]====]}
}
applicationsmenu[100] = {
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[Batti]====], [====[batti]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[EtherApe]====], [====[gksu etherape]====]},
{[====[Htop]====], [====[htop]====]},
{[====[IBus]====], [====[ibus-daemon --xim]====]},
{[====[Oracle VM VirtualBox]====], [====[VirtualBox]====]},
{[====[UXTerm]====], [====[uxterm]====]},
{[====[XTerm]====], [====[xterm]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[Bluetooth Device Setup]====], [====[bluetooth-wizard]====]},
{[====[Customize Look and Feel]====], [====[lxappearance]====]},
{[====[Desktop Preferences]====], [====[pcmanfm --desktop-pref]====]},
{[====[IBus Preferences]====], [====[ibus-setup]====]},
{[====[Network Connections]====], [====[nm-connection-editor]====]},
{[====[Preferred Applications]====], [====[libfm-pref-apps]====]},
{[====[Privilege granting]====], [====[gksu-properties]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]},
{[====[Startup Applications]====], [====[gnome-session-properties]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end